
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticnet

  backend:
    build: .
    container_name: search-backend
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    networks:
      - elasticnet
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
  elasticnet:
    driver: bridge
